name: CI

on: [push]

jobs:

  testGit:
    runs-on: ubuntu-latest
    steps:
    - uses: |
        actions/checkout@v1
        docker://microsoft/dotnet:2.2-sdk
    - name: testGit
      run: |
        pwd
