name: CI

on: [push]

jobs:

  testComplete:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir dist
        cd tst/backend
        dotnet publish -c Release -o ../../dist

    - uses: docker://angular/ngcontainer
    - run: |
        pwd
        ls
        cd tst/frontend
        npm install
        ng build
  
    - uses: docker://devorbitus/ubuntu-bash-jq-curl
    - run: |
        deployAccount=$(echo -n ${{ secrets.ROBOT_PW }} | base64)
        cd dist && zip -r ./../Artifacts.zip ./* && cd ..
        ls
        echo '>chmod<'
        chmod +x ./publish-github.sh
        echo '>publish script<'
        exec ./publish-github.sh -a $deployAccount -o 'JustinSchaffranek' -r 'tst-publish' -d 'dist' -m 'Updated with Github Actions' -f 'Artifacts.zip'
        
    - uses: docker://microsoft/dotnet:2.2-sdk
    - run: |
        pwd
        ls
