name: CI

on: [push]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build/deploy
      run: |
        deployAccount=$(echo -n ${{ secrets.ROBOT_PW }} | base64)
        mkdir dist
        cd tst
        dotnet build -c Release -o ../dist
        dotnet publish -c Release -o ../dist
        cd ..
        cd dist && zip -r ./../Artifacts.zip ./* && cd ..
        ls
        chmod +x ./publish-github.sh
        exec ./publish-github.sh -a $deployAccount -o 'JustinSchaffranek' -r 'tst-publish' -d 'dist' -m 'Updated from GitLab' -f 'Artifacts.zip'