name: CI

on: [push]

jobs:

  testGit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: testGit
      run: |
        ls
        echo ${{ github.ref }}
        echo ${{ github.event_name }}
        echo ${{ github.head_ref }}
        echo ${{ github.base_ref }}
