name: CI

on: [push]

jobs:

  testDocker:
    runs-on: ubuntu-latest
    steps:
    - uses: docker://microsoft/dotnet:2.2-sdk
    - name: list all directories and files
      run: |
        ls

  testComplete:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir dist
        cd tst
        dotnet publish -c Release -o ../dist
  
    - uses: docker://devorbitus/ubuntu-bash-jq-curl
    - run: |
        ls
        cd dist
        ls
        cd ..
        deployAccount=$(echo -n ${{ secrets.ROBOT_PW }} | base64)
        cd dist && zip -r ./../Artifacts.zip ./* && cd ..
        chmod +x ./publish-github.sh
        exec ./publish-github.sh -a $deployAccount -o 'JustinSchaffranek' -r 'tst-publish' -d 'dist' -m 'Updated with Github Actions' -f 'Artifacts.zip'
        
    - uses: docker://microsoft/dotnet:2.2-sdk
    - run: |
        pwd
        ls
