name: CI

on: [push]

jobs:
  test1:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: 1step1
      run: |
        mkdir dist
        cd tst
        dotnet build -c Release -o ../dist
        dotnet publish -c Release ../dist

  test2:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: 2step1
      run: |
        pwd
        cd tst
        dotnet build
