name: CI

on: [push]

jobs:
          
  buildAndDeploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir dist
        cd tst/frontend
        npm install
        npm install -g @angular/cli
        ng build --prod --progress true:  
        cd ../backend
        dotnet publish -c Release -o ../../dist
        cd ../../dist
        mkdir dummy
        
    - run: |
        cd dist
        pwd
        ls
        
