name: CI

on: [push]

jobs:

  docker:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        ls
        mkdir dist
        pwd
        docker run -it -v ./dist/:/dist justinschaffranek/ngbuild
        pwd
        ls

  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://justinschaffranek/ngbuild  
    - run: |
        cd tst/frontend
        ls
        npm install
        ng build --prod --progress true:  
        ls                
    - run: |
        mkdir dist
        cd tst/frontend
        npm install
        npm install -g @angular/cli
        ng build --prod --progress true:  
        cd ../backend
        dotnet publish -c Release -o ../../dist
        cd ../../dist
        mkdir dummy
     
  buildAndDeployStaging:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        mkdir dist
        cd tst/frontend
        npm install
        npm install -g @angular/cli
        ng build --prod --progress true:  
        cd ../backend
        dotnet publish -c Release -o ../../dist
        cd ../..
        export PATH="$PATH:/root/.dotnet/tools"
        dotnet tool install --global azzipgo --version 0.3.4
        pwd
        ls
        cd dist
        pwd
        ls
        cd ..
        azzipgo deploy-in-place -d dist/ -u dcc08599-210c-4495-94d0-dfeb1a8d1d88 -p -go0GxaxPH-qsv2@sSeDKxiQqPwt_B34 -t gksullust.com -s c23fb836-26ae-44c7-ba0b-c173ceaeb6e8 -g tst-ghactions-weu-rg-0 --site testghaction --target-slot production
