name: Build and Deploy with Artifacts upload/download

on: [push]

jobs:
  buildFrontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build frontend
      run: |
        cd tst/frontend
        npm install
        npm run build     
    - name: check paths
      run: |
        cd dist
        pwd
        ls
    - uses: actions/upload-artifact@master
      with:
        name: frontend
        path: tst/frontend/dist
  
  buildBackend:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: add dist directory
      run: mkdir dist  
    - name: build backend
      run: |
        cd tst/backend
        dotnet publish -c Release -o ../../dist        
    - name: check paths
      run: |
        cd dist
        pwd
        ls
    - uses: actions/upload-artifact@master
      with:
        name: backend
        path: dist/backend
