name: Build and Deploy with Artifacts upload/download

on: [push]

jobs:
  buildFrontend:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: build frontend
      run: |
        cd tst/frontend
        npm install
        npm run build     
    - name: check paths
      run: |
        cd tst/frontend/dist
        pwd
        ls
    - uses: actions/upload-artifact@master
      with:
        name: frontend
        path: tst/frontend/dist/frontend
  
  buildBackend:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: add dist directory
      run: mkdir dist  
    - name: build backend
      run: |
        cd tst/backend
        dotnet publish -c Release -o ../../dist        
    - name: check paths
      run: |
        cd dist
        pwd
        ls
    - uses: actions/upload-artifact@master
      with:
        name: backend
        path: dist

  DeployToAzure:
    runs-on: windows-latest
    needs: [buildFrontend, buildBackend]

    steps:
    - uses: actions/download-artifact@master
      with:
        name: frontend
    - uses: actions/download-artifact@master
      with:
        name: backend
    - name: prepare dist folder    
      run: |
        ls
        mkdir deploy
        move ./backend/* ./deploy
        echo "--> move backend:"
        ls ./dist
        echo "--> move frontend:"
        move ./frontend/* ./deploy
        ls ./dist
      
    - name: deploy to azure
      run: |
        dotnet tool install --global azzipgo --version 0.3.4
        azzipgo deploy-in-place -d deploy/ -u dcc08599-210c-4495-94d0-dfeb1a8d1d88 -p -go0GxaxPH-qsv2@sSeDKxiQqPwt_B34 -t gksullust.com -s c23fb836-26ae-44c7-ba0b-c173ceaeb6e8 -g tst-ghactions-weu-rg-0 --site testghaction --target-slot production
