name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        cd tst/frontend
        npm install
        npm run build
    - name: check
      run: |
        cd tst/frontend
        pwd
        ls
    - name: look inside dist
      run: |
        cd tst/frontend/dist
        pwd
        ls
    - name: look inside dist frontend
      run: |
        cd tst/frontend/dist/frontend
        pwd
        ls
    - name: move artifacts
      run: |
        cd tst/frontend/dist/frontend
        cp * ../../../../dist
    - name: check move
      run: |
        cd dist
        pwd
        ls
